// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYoReXVnzd_3vQpicdepsD-fo6H7udu4w',
    appId: '1:110340892416:web:283ca5af3367d61ebb35e5',
    messagingSenderId: '110340892416',
    projectId: 'catalogo-8e127',
    authDomain: 'catalogo-8e127.firebaseapp.com',
    storageBucket: 'catalogo-8e127.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYEL91j1NB1vscAOw6SQKIqBjxDAXOV18',
    appId: '1:110340892416:android:b87f56002302e4b3bb35e5',
    messagingSenderId: '110340892416',
    projectId: 'catalogo-8e127',
    storageBucket: 'catalogo-8e127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGPRjiaMrIagwuSUVnCEeW57Aw1xny_uI',
    appId: '1:110340892416:ios:db8ffb7c09f735e7bb35e5',
    messagingSenderId: '110340892416',
    projectId: 'catalogo-8e127',
    storageBucket: 'catalogo-8e127.firebasestorage.app',
    iosBundleId: 'com.example.catalogoDePeliculas',
  );

}